<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wlk</string>
		<string>wpgm</string>
	</array>
	<key>name</key>
	<string>Wollok</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(\b(and|or|not)\b)|(\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.))</string>
			<key>name</key>
			<string>keyword.operator.source.wollok</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>object|class|package|program|method|override|native|var|val|extends|new|if|else|elseif|this|import|null|true|false|return|throw|always|try</string>
			<key>name</key>
			<string>keyword.source.wollok</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.source.wollok</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.wollok</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.wollok</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.source.wollok</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\d{1,3}|.)</string>
					<key>name</key>
					<string>constant.character.escape.source.wollok</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.wollok</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.wollok</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\d{1,3}|.)</string>
					<key>name</key>
					<string>constant.character.escape.source.wollok</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(//).*</string>
					<key>name</key>
					<string>comment.line.double-slash.source.wollok</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.source.wollok</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.wollok</string>
	<key>uuid</key>
	<string>593a7982-2830-4b6c-99e1-e7b38fe99bc0</string>
</dict>
</plist>
